- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory

- copy:
    src: ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install Node.js 13"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash
    sudo apt install -y Node.js
        
    sudo npm install --global n
    sudo n 13.8.0

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: "Installing Node Dependencies"
#   shell: |
#     cd /home/ubuntu/backend
#     npm i

- name: Start the app
  shell: |
    export TYPEORM_ENTITIES=./backend/dist/modules/domain/**/*.entity{.ts,.js}
    export TYPEORM_HOST=localhost
    export TYPEORM_PORT=5532
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=password
    export TYPEORM_DATABASE=glee
    export TYPEORM_MIGRATIONS_DIR=./backend/dist/migrations
    export TYPEORM_MIGRATIONS=./backend/dist/migrations/*.ts
    pm2 stop default
    pm2 start -f /home/ubuntu/backend/dist/main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: Configure PM2 to start as service
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
